# Compiler and flags
CC = gcc
CFLAGS = -Wall -Wextra -std=c99

# Source and object files
SRC = main.c src/tokenizer.c src/file_io.c src/globals.c
OBJ = $(SRC:.c=.o)
TARGET = combo

# Build target
$(TARGET): $(OBJ)
	$(CC) $(OBJ) -o $(TARGET)

# Compile .c to .o (automatic dependency generation)
%.o: %.c
	$(CC) $(CFLAGS) -MMD -c $< -o $@

# Include dependency files generated by -MMD
-include $(OBJ:.o=.d)

# Clean object files, dependency files, and binary
clean:
	rm -f $(OBJ) $(OBJ:.o=.d)

